# Config file for automatic testing at travis-ci.org

language: python

dist: trusty

sudo: true

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"

install:
  - pip install tox
  - pip install tox-travis

script: tox
